name = "kirapass-api"
main = "src/index.ts"
compatibility_date = "2026-05-07"
account_id = "e3274a2e7b6c6a2b5e2d226d679ef696"

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"
KIRAPAY_BASE_URL = "https://api.kira-pay.com/api"
FRONTEND_URL = "https://kirapass.vercel.app"
FRONTEND_ORIGIN = "https://kirapass.vercel.app"
KIRAPAY_MOCK_MODE = "false"
MERCHANT_WALLET_ADDRESS = "0x2b585891B9bc6183f70e12Ae6413280E3304Ac07"
SETTLEMENT_CHAIN_ID = "8453"
SETTLEMENT_TOKEN_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"

[[d1_databases]]
binding = "DB"
database_name = "kirapass-db"
database_id = "facddc65-c73c-471f-9c57-b7c41f0fbf68"
preview_database_id = "kirapass-db-local"
