name = "kirapass-api"
main = "src/index.ts"
compatibility_date = "2026-05-07"
account_id = "e3274a2e7b6c6a2b5e2d226d679ef696"

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"
KIRAPAY_BASE_URL = "https://api.kira-pay.com/api"
KIRAPAY_CURRENCY = "USDC"
FRONTEND_URL = "https://kirapass.vercel.app"
FRONTEND_ORIGIN = "https://kirapass.vercel.app"
KIRAPAY_MOCK_MODE = "false"

[[d1_databases]]
binding = "DB"
database_name = "kirapass-db"
database_id = "facddc65-c73c-471f-9c57-b7c41f0fbf68"
preview_database_id = "kirapass-db-local"
